/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SetupDirectusRouteImport } from './routes/setup-directus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RRequestIdRouteImport } from './routes/r.$requestId'
import { Route as ApiDirectusSplatRouteImport } from './routes/api/directus.$'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupDirectusRoute = SetupDirectusRouteImport.update({
  id: '/setup-directus',
  path: '/setup-directus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RRequestIdRoute = RRequestIdRouteImport.update({
  id: '/r/$requestId',
  path: '/r/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectusSplatRoute = ApiDirectusSplatRouteImport.update({
  id: '/api/directus/$',
  path: '/api/directus/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/setup-directus': typeof SetupDirectusRoute
  '/success': typeof SuccessRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/api/directus/$': typeof ApiDirectusSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/setup-directus': typeof SetupDirectusRoute
  '/success': typeof SuccessRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/api/directus/$': typeof ApiDirectusSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/setup-directus': typeof SetupDirectusRoute
  '/success': typeof SuccessRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/api/directus/$': typeof ApiDirectusSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/audit'
    | '/login'
    | '/setup-directus'
    | '/success'
    | '/r/$requestId'
    | '/requests/$id'
    | '/api/directus/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/audit'
    | '/login'
    | '/setup-directus'
    | '/success'
    | '/r/$requestId'
    | '/requests/$id'
    | '/api/directus/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/agents'
    | '/audit'
    | '/login'
    | '/setup-directus'
    | '/success'
    | '/r/$requestId'
    | '/requests/$id'
    | '/api/directus/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AgentsRoute: typeof AgentsRoute
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRoute
  SetupDirectusRoute: typeof SetupDirectusRoute
  SuccessRoute: typeof SuccessRoute
  RRequestIdRoute: typeof RRequestIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  ApiDirectusSplatRoute: typeof ApiDirectusSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-directus': {
      id: '/setup-directus'
      path: '/setup-directus'
      fullPath: '/setup-directus'
      preLoaderRoute: typeof SetupDirectusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$requestId': {
      id: '/r/$requestId'
      path: '/r/$requestId'
      fullPath: '/r/$requestId'
      preLoaderRoute: typeof RRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/directus/$': {
      id: '/api/directus/$'
      path: '/api/directus/$'
      fullPath: '/api/directus/$'
      preLoaderRoute: typeof ApiDirectusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AgentsRoute: AgentsRoute,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRoute,
  SetupDirectusRoute: SetupDirectusRoute,
  SuccessRoute: SuccessRoute,
  RRequestIdRoute: RRequestIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  ApiDirectusSplatRoute: ApiDirectusSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
